"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { useLanguage } from "@/i18n";

function EnglishPolicy() {
  return (
    <>
      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings defined under the following conditions.
        The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>
      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li><strong>Developer</strong> (referred to as either &quot;the Developer&quot;, &quot;I&quot;, &quot;Me&quot; or &quot;My&quot; in this Policy) refers to the individual who created and maintains MeetZap.</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the MeetZap website.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>You</strong> means the individual accessing or using the Service.</li>
      </ul>

      <h2>Collecting and Using Your Data</h2>
      <h3>Types of Data Collected</h3>
      <h4>Event and Availability Data</h4>
      <p>
        When using MeetZap, you may provide the following information voluntarily:
      </p>
      <ul>
        <li>Event titles and descriptions</li>
        <li>Selected dates and time ranges</li>
        <li>Your display name (when submitting availability)</li>
        <li>Your time slot selections</li>
      </ul>
      <p>
        MeetZap does not require account registration or login. No email address, password, or other personal
        credentials are collected.
      </p>

      <h4>Usage Data</h4>
      <p>
        Usage Data may be collected automatically when using the Service. This may include information such as
        your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages
        of the Service that you visit, the time and date of your visit, time spent on those pages, and other
        diagnostic data.
      </p>

      <h3>Use of Your Data</h3>
      <p>I may use the data you provide for the following purposes:</p>
      <ul>
        <li><strong>To provide and maintain the Service</strong>, including displaying event details and participant availability to those who have the event link.</li>
        <li><strong>To improve the Service</strong>, by analyzing usage patterns and identifying areas for improvement.</li>
        <li><strong>To ensure the security of the Service</strong>, by monitoring for abuse or unauthorized use.</li>
      </ul>

      <h3>Retention of Your Data</h3>
      <p>
        Event and availability data is stored temporarily for scheduling purposes. Events and their associated
        data may be automatically deleted after a period of inactivity. Usage Data is generally retained for a
        shorter period, except when used to improve security or functionality of the Service.
      </p>

      <h3>Sharing of Your Data</h3>
      <p>
        MeetZap does not sell, trade, or rent your data to third parties. Event and availability information
        is accessible to anyone who has the unique event link. You should only share event links with people
        you intend to coordinate with.
      </p>

      <h2>Cookies and Tracking Technologies</h2>
      <p>
        MeetZap may use cookies or similar technologies to remember your language preference and improve your
        experience. These are limited to essential functionality. I do not use advertising cookies or
        third-party tracking services.
      </p>

      <h2>Security of Your Data</h2>
      <p>
        The security of your data is important to me. While I strive to use commercially acceptable means to
        protect your data, no method of transmission over the Internet or method of electronic storage is 100%
        secure. I cannot guarantee its absolute security.
      </p>

      <h2>Children&apos;s Privacy</h2>
      <p>
        The Service does not address anyone under the age of 13. I do not knowingly collect personally
        identifiable information from anyone under the age of 13. If you are a parent or guardian and you are
        aware that your child has provided me with Personal Data, please contact me.
      </p>

      <h2>Links to Other Websites</h2>
      <p>
        The Service may contain links to other websites that are not operated by me. If you click on a third-party
        link, you will be directed to that third party&apos;s site. I strongly advise you to review the Privacy
        Policy of every site you visit. I have no control over and assume no responsibility for the content,
        privacy policies, or practices of any third-party sites or services.
      </p>

      <h2>Changes to This Privacy Policy</h2>
      <p>
        I may update this Privacy Policy from time to time. I will notify you of any changes by posting the new
        Privacy Policy on this page and updating the &quot;Last updated&quot; date. You are advised to review this
        Privacy Policy periodically for any changes.
      </p>

      <h2>Contact Me</h2>
      <p>
        If you have any questions about this Privacy Policy, you can reach me via{" "}
        <a href="https://x.com/kasperzhang" target="_blank" rel="noopener noreferrer">@kasperzhang on X (Twitter)</a>.
      </p>
    </>
  );
}

function ChinesePolicy() {
  return (
    <>
      <h2>解释与定义</h2>
      <h3>解释</h3>
      <p>
        首字母大写的词语在以下条件下具有特定含义。无论以单数还是复数形式出现，以下定义具有相同含义。
      </p>
      <h3>定义</h3>
      <p>就本隐私政策而言：</p>
      <ul>
        <li><strong>开发者</strong>（在本政策中也称为"我"）是指创建和维护 MeetZap 的个人。</li>
        <li><strong>设备</strong>是指任何可以访问本服务的设备，如电脑、手机或平板电脑。</li>
        <li><strong>个人数据</strong>是指与已识别或可识别个人相关的任何信息。</li>
        <li><strong>服务</strong>是指 MeetZap 网站。</li>
        <li><strong>使用数据</strong>是指自动收集的数据，由使用服务产生或来自服务基础设施本身（例如页面访问时长）。</li>
        <li><strong>您</strong>是指访问或使用本服务的个人。</li>
      </ul>

      <h2>数据的收集与使用</h2>
      <h3>收集的数据类型</h3>
      <h4>活动与空闲时间数据</h4>
      <p>使用 MeetZap 时，您可能自愿提供以下信息：</p>
      <ul>
        <li>活动标题和描述</li>
        <li>选择的日期和时间范围</li>
        <li>您的显示名称（提交空闲时间时）</li>
        <li>您的时段选择</li>
      </ul>
      <p>
        MeetZap 不要求注册账户或登录。我不收集电子邮件地址、密码或其他个人凭证。
      </p>

      <h4>使用数据</h4>
      <p>
        使用本服务时可能会自动收集使用数据。这可能包括您设备的互联网协议地址（如 IP 地址）、浏览器类型、浏览器版本、您访问的服务页面、访问的时间和日期、在这些页面上花费的时间以及其他诊断数据。
      </p>

      <h3>数据的使用</h3>
      <p>我可能将您提供的数据用于以下目的：</p>
      <ul>
        <li><strong>提供和维护服务</strong>，包括向拥有活动链接的人显示活动详情和参与者的空闲时间。</li>
        <li><strong>改进服务</strong>，通过分析使用模式并确定改进领域。</li>
        <li><strong>确保服务安全</strong>，通过监控滥用或未经授权的使用。</li>
      </ul>

      <h3>数据的保留</h3>
      <p>
        活动和空闲时间数据为临时存储，仅用于日程安排目的。活动及其相关数据可能在一段时间不活动后自动删除。使用数据通常保留较短时间，除非用于改善服务的安全性或功能。
      </p>

      <h3>数据的共享</h3>
      <p>
        MeetZap 不会将您的数据出售、交易或出租给第三方。活动和空闲时间信息可供拥有唯一活动链接的任何人访问。您应仅与您打算协调日程的人分享活动链接。
      </p>

      <h2>Cookie 和跟踪技术</h2>
      <p>
        MeetZap 可能使用 Cookie 或类似技术来记住您的语言偏好并改善您的体验。这些仅限于基本功能。我不使用广告 Cookie 或第三方跟踪服务。
      </p>

      <h2>数据安全</h2>
      <p>
        您的数据安全对我非常重要。虽然我努力使用商业上可接受的方式保护您的数据，但互联网上的传输方式或电子存储方式都不是 100% 安全的。我无法保证其绝对安全性。
      </p>

      <h2>儿童隐私</h2>
      <p>
        本服务不面向 13 岁以下的任何人。我不会故意收集 13 岁以下任何人的个人身份信息。如果您是家长或监护人，并且您知道您的孩子向我提供了个人数据，请与我联系。
      </p>

      <h2>其他网站的链接</h2>
      <p>
        本服务可能包含指向非我运营的其他网站的链接。如果您点击第三方链接，您将被引导至该第三方的网站。我强烈建议您查看您访问的每个网站的隐私政策。我对任何第三方网站或服务的内容、隐私政策或做法不承担任何控制权或责任。
      </p>

      <h2>本隐私政策的变更</h2>
      <p>
        我可能会不时更新本隐私政策。我将通过在此页面上发布新的隐私政策并更新"最后更新"日期来通知您任何变更。建议您定期查看本隐私政策以了解任何变更。
      </p>

      <h2>联系我</h2>
      <p>
        如果您对本隐私政策有任何疑问，可以通过{" "}
        <a href="https://x.com/kasperzhang" target="_blank" rel="noopener noreferrer">X (Twitter) 上的 @kasperzhang</a>{" "}
        联系我。
      </p>
    </>
  );
}

export default function PrivacyPage() {
  const { t, locale } = useLanguage();

  return (
    <main className="min-h-screen bg-[#FFF8E7]">
      <div className="container mx-auto px-4 py-12 max-w-2xl">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm font-bold text-black hover:text-neutral-600 transition-colors mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          {t.privacy.backToHome}
        </Link>

        <div className="bg-white border-2 border-black rounded-xl p-8 shadow-[4px_4px_0px_0px_#000] policy-content">
          <h1 className="text-2xl font-black mb-1">{t.privacy.title}</h1>
          <p className="text-xs text-neutral-400 mb-6">{t.privacy.lastUpdated}</p>

          {locale === "zh" ? <ChinesePolicy /> : <EnglishPolicy />}
        </div>
      </div>
    </main>
  );
}
